"""Add is_reference to Video

Revision ID: 79a9948f4426
Revises: ace8fa7fa075
Create Date: 2025-12-01 10:26:26.313012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a9948f4426'
down_revision: Union[str, None] = 'ace8fa7fa075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('is_reference', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'is_reference')
    # ### end Alembic commands ###
