"""Add user validation status and permissions

Revision ID: 89b0e3ae8696
Revises: b2c3d4e5f6a7
Create Date: 2025-12-01 23:38:25.743948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89b0e3ae8696'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('chat_messages') # KEEPING CHAT TABLES
    # op.drop_table('chat_sessions') # KEEPING CHAT TABLES
    
    # Create Enum type explicitly
    validation_status = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='validation_status')
    validation_status.create(op.get_bind())
    
    op.add_column('users', sa.Column('validation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='validation_status'), nullable=False, server_default='PENDING'))
    op.add_column('users', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'validation_status')
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name='chat_messages_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    # ### end Alembic commands ###
