"""add_user_profile_fields

Revision ID: fa4ea57f6581
Revises: 3aaacb5104ee
Create Date: 2025-11-30 11:06:08.876766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4ea57f6581'
down_revision: Union[str, None] = '3aaacb5104ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enums explicitly
    handedness_enum = sa.Enum('RIGHT', 'LEFT', name='handedness')
    handedness_enum.create(op.get_bind(), checkfirst=True)
    
    backhand_style_enum = sa.Enum('ONE_HANDED', 'TWO_HANDED', name='backhandstyle')
    backhand_style_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('ranking', sa.String(), nullable=True))
    op.add_column('users', sa.Column('fft_club', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tenup_profile_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('handedness', handedness_enum, nullable=True))
    op.add_column('users', sa.Column('backhand_style', backhand_style_enum, nullable=True))
    op.add_column('users', sa.Column('play_style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'play_style')
    op.drop_column('users', 'backhand_style')
    op.drop_column('users', 'handedness')
    op.drop_column('users', 'tenup_profile_url')
    op.drop_column('users', 'fft_club')
    op.drop_column('users', 'ranking')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    
    # Drop Enums
    sa.Enum(name='backhandstyle').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='handedness').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
